# Generated by Django 4.1 on 2023-12-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['id'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
    ]
