# Generated by Django 4.1 on 2023-12-07 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarios', models.CharField(max_length=50, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Cadastro de Usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UsuariosSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=50, verbose_name='CPF')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.solicitante')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
            options={
                'verbose_name': 'UsuariosSolicitante',
                'verbose_name_plural': 'UsuariosSolicitantes',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='usuarios',
            name='usuarios_solicitante',
            field=models.ManyToManyField(blank=True, through='usuarios.UsuariosSolicitante', to='solicitante.solicitante'),
        ),
    ]
