# Generated by Django 4.1 on 2023-12-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitante',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
