# Generated by Django 4.1 on 2023-12-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitante', '0002_alter_solicitante_options_remove_solicitante_nome_and_more'),
        ('endereco', '0002_alter_endereco_options'),
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='solicitacao_endereco',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='cpf',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='solicitante.solicitante'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='localizacao',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco'),
        ),
        migrations.DeleteModel(
            name='SolicitacaoEndereco',
        ),
    ]
