# Generated by Django 4.1 on 2023-12-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_remove_solicitacao_solicitacao_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='localizacao',
        ),
    ]
