# Generated by Django 4.1 on 2023-12-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitacoes', '0002_remove_solicitacao_solicitacao_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('departamento', models.CharField(blank=True, choices=[('Departamento de Infraestrutura', 'Departamento de Infraestrutura'), ('Departamento de Iluminação Pública', 'Departamento de Iluminação Pública'), ('Departamento de Mobilidade Urbana', 'Departamento de Mobilidade Urbana'), ('Departamento de Infraestrutura', 'Departamento de Infraestrutura'), ('Departamento de Serviços Ambientais e Limpeza Urbana', 'Departamento de Serviços Ambientais e Limpeza Urbana'), ('Departamento de Água e Saneamento', 'Departamento de Água e Saneamento'), ('Departamento de Energia', 'Departamento de Energia'), ('Selecionar', 'Selecionar')], default='Selecionar', max_length=100, null=True, verbose_name='Departamento')),
                ('rua', models.CharField(max_length=200, verbose_name='Rua')),
                ('numero', models.IntegerField(max_length=5, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('id_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacao')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_on'],
            },
        ),
    ]
