# Generated by Django 4.1 on 2023-12-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='description',
        ),
        migrations.AddField(
            model_name='departamento',
            name='descricao',
            field=models.TextField(default='Nulo', max_length=80, verbose_name='Descricao'),
        ),
    ]
