# Generated by Django 4.1 on 2023-12-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_remove_departamento_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descricao',
            field=models.TextField(default='---', max_length=80, verbose_name='Descricao'),
        ),
    ]
