# Generated by Django 4.1 on 2023-12-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_servicos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['id'], 'verbose_name': 'Avaliacao', 'verbose_name_plural': 'Avaliacoes'},
        ),
        migrations.DeleteModel(
            name='Servicos',
        ),
    ]
