# Generated by Django 4.1 on 2023-12-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiais',
            options={'ordering': ['id'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
    ]
